# SLM with ultravox & llama3.1, trained wtih knowledge distillation.
# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
audio_model: "openai/whisper-small"

adapter_type: "CFORMER"
loss_config:
  loss_weights: 
    Response_KL: 1
  logging_steps: 10

max_steps: 14400 # x8x24 
lr_warmup_steps: 1000
lr:  1e-3
weight_decay: 0.05
logging_steps: 10

train_dataset_args:
  shuffle: True
  batch_size: 12
train_dataset_configs:
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100" # 28_539 samples
      - "train.360" # 104_014 samples
    num_samples: 132_553
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500" # 148_688 samples
    num_samples: 148_688
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
  - path: "fixie-ai/common_voice_17_0"
    name: "en"
    splits:
      - "train" # 1_101_170 samples
    num_samples: 1_101_170
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text_proc.format_asr_text(sentence) }}"
    weight: 8


val_dataset_args:
  batch_size: 40
val_dataset_configs:
  - alias: "covost2-en_zh-val"
    path: "fixie-ai/covost2"
    name: "en_zh-CN"
    splits:
      - "validation"
    active_samples: 200
    num_samples: 15531
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Chinese"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
  - alias: "covost2-zh_en-val"
    path: "fixie-ai/covost2"
    name: "zh-CN_en"
    splits:
      - "validation"
    active_samples: 200
    num_samples: 4843
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
  - alias: "peoples_speech-val"
    path: "fixie-ai/peoples_speech"
    name: "clean"
    splits:
      - "train" # 1_501_271 samples
    active_samples: 200
    num_samples: 1_501_271
    user_template: "Transcribe\n<|audio|>"
    assistant_template: "{{ text_proc.format_asr_text(text) }}"
    transcript_template: "{{ text_proc.format_asr_text(text) }}"
  - alias: "covost2-en_zh-text-val"
    path: "fixie-ai/covost2"
    name: "en_zh-CN"
    splits:
      - "validation"
    active_samples: 200
    num_samples: 15531
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n{{ sentence }}"
    user_template_args:
      target: "Chinese"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    audio_field: null
  - alias: "covost2-zh_en-text-val"
    path: "fixie-ai/covost2"
    name: "zh-CN_en"
    splits:
      - "validation"
    active_samples: 200
    num_samples: 4843
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n{{ sentence }}"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    audio_field: null
  - alias: "peoples_speech-text-val"
    path: "fixie-ai/peoples_speech"
    name: "clean"
    splits:
      - "train" # 1_501_271 samples
    active_samples: 200
    num_samples: 1_501_271
    user_template: "Transcribe\n{{ text_proc.format_asr_text(text) }}"
    assistant_template: "{{ text_proc.format_asr_text(text) }}"
    transcript_template: "{{ text_proc.format_asr_text(text) }}"
    audio_field: null