# SLM with ultravox & llama3.1, trained wtih knowledge distillation.
# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
audio_model: "openai/whisper-medium"
# model_load_dir: "wandb://fixie/ultravox/model-zhuang.2024-08-12-ultravox.input_kd-1d:v1"
# resume_from_checkpoint: True

adapter_type: "CFORMER"
loss_config:
  loss_weights: 
    Response_KL: 1
    Input_KL: 1

max_steps: 14400 # x8x24 

train_dataset_args:
  shuffle: True
  batch_size: 12
train_dataset_configs:
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100" # 28_539 samples
      - "train.360" # 104_014 samples
    num_samples: 132_553
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500" # 148_688 samples
    num_samples: 148_688
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
  - path: "fixie-ai/common_voice_17_0"
    name: "en"
    splits:
      - "train" # 1_101_170 samples
    num_samples: 1_101_170
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text_proc.format_asr_text(sentence) }}"