# SLM with ultravox & llama3.1, trained wtih knowledge distillation.
# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
audio_model: "openai/whisper-medium"
model_load_dir: "wandb://fixie/ultravox/model-zhuang.2024-08-12-ultravox.input_kd-1d:v1"
resume_from_checkpoint: True

adapter_type: "CFORMER"
loss_config:
  loss_weights: 
    Response_KL: 1
    Input_KL: 1

max_steps: 14400 # x8x24 = 2,764,800

train_dataset_args:
  shuffle: True
  batch_size: 24
train_dataset_configs:
# continuation
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100" # 28_539 samples
      - "train.360" # 104_014 samples
    num_samples: 132_553
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ text }}"
    weight: 1
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500" # 148_688 samples
    num_samples: 148_688
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ text }}"
    weight: 1
  - path: "fixie-ai/peoples_speech"
    name: "clean"
    splits:
      - "train" # 1_501_271 samples
    num_samples: 1_501_271
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ text_proc.format_asr_text(text) }}"
    weight: 8
  - path: "fixie-ai/common_voice_17_0"
    name: "en"
    splits:
      - "train" # 1_101_170 samples
    num_samples: 1_101_170
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ text_proc.format_asr_text(sentence) }}"
    weight: 8
  - path: "fixie-ai/common_voice_17_0"
    name: "ar"
    splits:
      - "train" # 28_369 samples
    num_samples: 28_369
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ sentence }}"
    weight: 0.2
  - path: "fixie-ai/common_voice_17_0"
    name: "de"
    splits:
      - "train" # 589_100 samples
    num_samples: 589_100
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ sentence }}"
    weight: 4
  - path: "fixie-ai/common_voice_17_0"
    name: "es"
    splits:
      - "train" # 336_846 samples
    num_samples: 336_846
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ sentence }}"
    weight: 3
  - path: "fixie-ai/common_voice_17_0"
    name: "fr"
    splits:
      - "train" # 558_054 samples
    num_samples: 558_054
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ sentence }}"
    weight: 4
  - path: "fixie-ai/common_voice_17_0"
    name: "it"
    splits:
      - "train" # 169_771 samples
    num_samples: 169_771
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ sentence }}"
    weight: 1.2
  - path: "fixie-ai/common_voice_17_0"
    name: "ja"
    splits:
      - "train" # 10_039 samples
    num_samples: 10_039
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ sentence }}"
    weight: 0.1
  - path: "fixie-ai/common_voice_17_0"
    name: "pt"
    splits:
      - "train" # 21_968 samples
    num_samples: 21_968
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ sentence }}"
    weight: 0.2
  - path: "fixie-ai/common_voice_17_0"
    name: "ru"
    splits:
      - "train" # 26_377 samples
    num_samples: 26_377
    user_template: "<|audio|>"
    assistant_template: ""
    transcript_template: "{{ sentence }}"
    weight: 0.2
  