text_model: "meta-llama/Meta-Llama-3-8B-Instruct"
audio_model: "facebook/wav2vec2-base-960h"

stop_strategy: "LAST_EXHAUSTED"

train_on_inputs: False

val_steps: 1000

optimizer: "adamw_torch"  # options: adamw_torch, adamw_bnb_8bit
lr_scheduler: "cosine"  # options: linear, cosine, cosine_with_restarts, etc.
lr:  2.e-3
grad_accum_steps: 1
lr_warmup_steps: 1000
max_steps: 10_000

save_steps: 0.25
logging_steps: 100

report_logs_to: ["tensorboard", "wandb"]

