text_model: "meta-llama/Meta-Llama-3-8B-Instruct"
audio_model: "facebook/wav2vec2-base-960h"

stop_strategy: "LAST_EXHAUSTED"

train_on_inputs: False

val_steps: 1000

optimizer: "adamw_torch"  # options: adamw_torch, adamw_bnb_8bit
lr_scheduler: "cosine"  # options: linear, cosine, cosine_with_restarts, etc.
lr:  2.e-3
grad_accum_steps: 1
lr_warmup_steps: 1000
max_steps: 10_000

save_steps: 0.25
logging_steps: 100

report_logs_to: ["tensorboard", "wandb"]

val_dataset_args:
  batch_size: 40
val_dataset_configs:
  - alias: "covost2-en_zh-val"
    path: "fixie-ai/covost2"
    name: "en_zh-CN"
    splits:
      - "validation"
    active_samples: 200
    num_samples: 15531
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Chinese"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
  - alias: "covost2-zh_en-val"
    path: "fixie-ai/covost2"
    name: "zh-CN_en"
    splits:
      - "validation"
    active_samples: 200
    num_samples: 4843
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"

eval_dataset_args:
  batch_size: 40
  max_tokens: 512
eval_dataset_configs:
  - alias: "covost2-en_de-test-2k"
    path: "fixie-ai/covost2"
    name: "en_de"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "German"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    active_samples: 2000
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-en_zh-test-2k"
    path: "fixie-ai/covost2"
    name: "en_zh-CN"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Chinese"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    active_samples: 2000
    num_samples: 15531
    eval_config:
      metric: "bleu"
      args:
        tokenize: "zh"
  - alias: "covost2-en_ar-test-2k"
    path: "fixie-ai/covost2"
    name: "en_ar"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Arabic"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    active_samples: 2000
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-en_ca-test-2k"
    path: "fixie-ai/covost2"
    name: "en_ca"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Catalan"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    active_samples: 2000
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-es_en-test-2k"
    path: "fixie-ai/covost2"
    name: "es_en"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    active_samples: 2000
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-ru_en-test-2k"
    path: "fixie-ai/covost2"
    name: "ru_en"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    active_samples: 2000
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-zh_en-test-2k"
    path: "fixie-ai/covost2"
    name: "zh-CN_en"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    active_samples: 2000
    num_samples: 15531
    eval_config:
      metric: "bleu"