# SLM with ultravox & llama3.1, trained wtih knowledge distillation.
exp_name: "ultravox-v0_4"

# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
audio_model: "openai/whisper-medium"

# device: "cpu"
# data_type: "float32"

loss_config:
  # Choose from ["KL_Divergence", "CrossEntropy"], default is "KL_Divergence"
  loss_function: "KL_Divergence"

report_logs_to: ["tensorboard"]

max_steps: 14400 # x8x24 = 2,764,800

train_dataset_args:
  shuffle: True
  batch_size: 24
val_dataset_args:
  batch_size: 24
eval_dataset_args:
  batch_size: 40
  max_tokens: 512

train_dataset_configs:
# continuation
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100" # 28_539 samples
      - "train.360" # 104_014 samples
    num_samples: 132_553
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
    weight: 1
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500" # 148_688 samples
    num_samples: 148_688
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
    weight: 1
  - path: "fixie-ai/peoples_speech"
    name: "clean"
    splits:
      - "train" # 1_501_271 samples
    num_samples: 1_501_271
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text_proc.format_asr_text(text) }}"
    weight: 8
  - path: "fixie-ai/common_voice_17_0"
    name: "en"
    splits:
      - "train" # 1_101_170 samples
    num_samples: 1_101_170
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text_proc.format_asr_text(sentence) }}"
    weight: 8
  - path: "fixie-ai/common_voice_17_0"
    name: "ar"
    splits:
      - "train" # 28_369 samples
    num_samples: 28_369
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ sentence }}"
    weight: 0.2
  - path: "fixie-ai/common_voice_17_0"
    name: "de"
    splits:
      - "train" # 589_100 samples
    num_samples: 589_100
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ sentence }}"
    weight: 4
  - path: "fixie-ai/common_voice_17_0"
    name: "es"
    splits:
      - "train" # 336_846 samples
    num_samples: 336_846
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ sentence }}"
    weight: 3
  - path: "fixie-ai/common_voice_17_0"
    name: "fr"
    splits:
      - "train" # 558_054 samples
    num_samples: 558_054
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ sentence }}"
    weight: 4
  - path: "fixie-ai/common_voice_17_0"
    name: "it"
    splits:
      - "train" # 169_771 samples
    num_samples: 169_771
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ sentence }}"
    weight: 1.2
  - path: "fixie-ai/common_voice_17_0"
    name: "ja"
    splits:
      - "train" # 10_039 samples
    num_samples: 10_039
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ sentence }}"
    weight: 0.1
  - path: "fixie-ai/common_voice_17_0"
    name: "pt"
    splits:
      - "train" # 21_968 samples
    num_samples: 21_968
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ sentence }}"
    weight: 0.2
  - path: "fixie-ai/common_voice_17_0"
    name: "ru"
    splits:
      - "train" # 26_377 samples
    num_samples: 26_377
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ sentence }}"
    weight: 0.2
# ASR task
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100" # 28_539 samples
      - "train.360" # 104_014 samples
    num_samples: 132_553
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text }}"
    transcript_template: "{{ text }}"
    weight: 0.1
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500" # 148_688 samples
    num_samples: 148_688
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text }}"
    transcript_template: "{{ text }}"
    weight: 0.1
  - path: "fixie-ai/peoples_speech"
    name: "clean"
    splits:
      - "train" # 1_501_271 samples
    num_samples: 1_501_271
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(text) }}"
    transcript_template: "{{ text_proc.format_asr_text(text) }}"
    weight: 0.8
  - path: "fixie-ai/common_voice_17_0"
    name: "en"
    splits:
      - "train" # 1_101_170 samples
    num_samples: 1_101_170
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ text_proc.format_asr_text(sentence) }}"
    weight: 0.8
  - path: "fixie-ai/common_voice_17_0"
    name: "ar"
    splits:
      - "train" # 28_369 samples
    num_samples: 28_369
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ sentence }}"
    weight: 0.02
  - path: "fixie-ai/common_voice_17_0"
    name: "de"
    splits:
      - "train" # 589_100 samples
    num_samples: 589_100
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ sentence }}"
    weight: 0.4
  - path: "fixie-ai/common_voice_17_0"
    name: "es"
    splits:
      - "train" # 336_846 samples
    num_samples: 336_846
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ sentence }}"
    weight: 0.3
  - path: "fixie-ai/common_voice_17_0"
    name: "fr"
    splits:
      - "train" # 558_054 samples
    num_samples: 558_054
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ sentence }}"
    weight: 0.4
  - path: "fixie-ai/common_voice_17_0"
    name: "it"
    splits:
      - "train" # 169_771 samples
    num_samples: 169_771
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ sentence }}"
    weight: 0.12
  - path: "fixie-ai/common_voice_17_0"
    name: "ja"
    splits:
      - "train" # 10_039 samples
    num_samples: 10_039
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ sentence }}"
    weight: 0.01
  - path: "fixie-ai/common_voice_17_0"
    name: "pt"
    splits:
      - "train" # 21_968 samples
    num_samples: 21_968
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ sentence }}"
    weight: 0.02
  - path: "fixie-ai/common_voice_17_0"
    name: "ru"
    splits:
      - "train" # 26_377 samples
    num_samples: 26_377
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ sentence }}"
    weight: 0.02



val_dataset_configs:
  - path: "fixie-ai/librispeech_asr"
    alias: "librispeech-cont-val"
    name: "clean"
    splits:
      - "validation"
    active_samples: 1000
    num_samples: 2703
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
  - path: "fixie-ai/covost2"
    alias: "covost2-en_zh-val"
    name: "en_zh-CN"
    splits:
      - "validation"
    active_samples: 1000
    num_samples: 15531
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Chinese"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
  - path: "fixie-ai/covost2"
    alias: "covost2-zh_en-val"
    name: "zh-CN_en"
    splits:
      - "validation"
    active_samples: 1000
    num_samples: 4843
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"

eval_dataset_configs:
  - alias: "covost2-en_de.2k"
    path: "fixie-ai/covost2"
    name: "en_de"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "German"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 2000
    total_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-en_zh.2k"
    path: "fixie-ai/covost2"
    name: "en_zh-CN"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Chinese"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 2000
    total_samples: 15531
    eval_config:
      metric: "bleu"
      args:
        tokenize: "zh"
  - alias: "covost2-en_ar.2k"
    path: "fixie-ai/covost2"
    name: "en_ar"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Arabic"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 2000
    total_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-en_ca.2k"
    path: "fixie-ai/covost2"
    name: "en_ca"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Catalan"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 2000
    total_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-es_en.2k"
    path: "fixie-ai/covost2"
    name: "es_en"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 2000
    total_samples: 13221
    eval_config:
      metric: "bleu"
  - alias: "covost2-ru_en.2k"
    path: "fixie-ai/covost2"
    name: "ru_en"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 2000
    total_samples: 6300
    eval_config:
      metric: "bleu"
  - alias: "covost2-zh_en.2k"
    path: "fixie-ai/covost2"
    name: "zh-CN_en"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 2000
    total_samples: 4898
    eval_config:
      metric: "bleu"