# SLM with ultravox & llama3.1, trained wtih knowledge distillation.
exp_name: "ultravox-v0_4"

# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
audio_model: "openai/whisper-medium"

loss_config:
  # Choose from ["KL_Divergence", "CrossEntropy"], default is "KL_Divergence"
  loss_function: "KL_Divergence"

# Temporarily remove heysquad_human from val_sets as it causes the training to fail.
val_sets: ["anyinstruct", "soda", "peoplespeech"]

batch_size: 24
max_steps: 14400 # x8x24 = 2,764,800

interleave_datasets:
  stop_strategy: "last_exhausted"
  datasets_with_multiplier: 
    # continuation
    - dataset: 
        path: "fixie-ai/librispeech_asr"
        name: "clean"
        splits:
          - "train.100" # 28_539 samples
          - "train.360" # 104_014 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ text }}"
        total_samples: 132553
      multiplier: 1
    - dataset:
        path: "fixie-ai/librispeech_asr"
        name: "other"
        splits:
          - "train.500" # 148_688 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ text }}"
        total_samples: 148688
      multiplier: 1
    - dataset:
        path: "fixie-ai/peoples_speech"
        name: "clean"
        splits:
          - "train" # 1_501_271 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ text_proc.format_asr_text(text) }}"
        total_samples: 1501271
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "en"
        splits:
          - "train" # 1_101_170 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ text_proc.format_asr_text(sentence) }}"
        total_samples: 1101170
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "ar"
        splits:
          - "train" # 28_369 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ sentence }}"
        total_samples: 28369
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "de"
        splits:
          - "train" # 589_100 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ sentence }}"
        total_samples: 589100
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "es"
        splits:
          - "train" # 336_846 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ sentence }}"
        total_samples: 336846
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "fr"
        splits:
          - "train" # 558_054 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ sentence }}"
        total_samples: 558054
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "it"
        splits:
          - "train" # 169_771 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ sentence }}"
        total_samples: 169771
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "ja"
        splits:
          - "train" # 10_039 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ sentence }}"
        total_samples: 10039
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "pt"
        splits:
          - "train" # 21_968 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ sentence }}"
        total_samples: 21968
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "ru"
        splits:
          - "train" # 26_377 samples
        user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
        assistant_template: "{{ continuation }}"
        transcript_template: "{{ sentence }}"
        total_samples: 2637
      multiplier: 1
  # ASR task
    - dataset:
        path: "fixie-ai/librispeech_asr"
        name: "clean"
        splits:
          - "train.100" # 28_539 samples
          - "train.360" # 104_014 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text }}"
        transcript_template: "{{ text }}"
        total_samples: 132553
      multiplier: 1
    - dataset:
        path: "fixie-ai/librispeech_asr"
        name: "other"
        splits:
          - "train.500" # 148_688 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text }}"
        transcript_template: "{{ text }}"
        total_samples: 148688
      multiplier: 1
    - dataset:
        path: "fixie-ai/peoples_speech"
        name: "clean"
        splits:
          - "train" # 1_501_271 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(text) }}"
        transcript_template: "{{ text_proc.format_asr_text(text) }}"
        total_samples: 1501271
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "en"
        splits:
          - "train" # 1_101_170 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
        transcript_template: "{{ text_proc.format_asr_text(sentence) }}"
        total_samples: 1101170
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "ar"
        splits:
          - "train" # 28_369 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
        transcript_template: "{{ sentence }}"
        total_samples: 28369
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "de"
        splits:
          - "train" # 589_100 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
        transcript_template: "{{ sentence }}"
        total_samples: 589100
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "es"
        splits:
          - "train" # 336_846 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
        transcript_template: "{{ sentence }}"
        total_samples: 336846
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "fr"
        splits:
          - "train" # 558_054 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
        transcript_template: "{{ sentence }}"
        total_samples: 558054
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "it"
        splits:
          - "train" # 169_771 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
        transcript_template: "{{ sentence }}"
        total_samples: 169771
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "ja"
        splits:
          - "train" # 10_039 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
        transcript_template: "{{ sentence }}"
        total_samples: 10039
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "pt"
        splits:
          - "train" # 21_968 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
        transcript_template: "{{ sentence }}"
        total_samples: 21968
      multiplier: 1
    - dataset:
        path: "fixie-ai/common_voice_17_0"
        name: "ru"
        splits:
          - "train" # 26_377 samples
        user_template: "{{ dataset._get_transcribe_prompt() }}"
        assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
        transcript_template: "{{ sentence }}"
        total_samples: 26377
      multiplier: 1
