# SLM with ultravox & llama3.1, trained wtih knowledge distillation.
# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Llama-3.2-1B-Instruct"
audio_model: "openai/whisper-small"

loss_config:
  loss_function: "KL_Divergence"

train_sets:
  - name: librispeech-clean-continuation

val_sets:
  - name: covost2-en-de

num_samples: 1000
batch_size: 10

lr: 1e-3
lr_warmup_steps: 1000
max_steps: -1
num_epochs: 2


