model: "fixie-ai/ultravox-v0_4"
report_logs_to: ["wandb"]
output_dir: "./output"
eval_dataset_args:
  batch_size: 40
  max_tokens: 512
eval_dataset_configs:
  - alias: "covost2-en_de"
    path: "fixie-ai/covost2"
    name: "en_de"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "German"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-en_zh"
    path: "fixie-ai/covost2"
    name: "en_zh-CN"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Chinese"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 15531
    eval_config:
      metric: "bleu"
      args:
        tokenize: "zh"
  - alias: "covost2-en_ar"
    path: "fixie-ai/covost2"
    name: "en_ar"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Arabic"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-en_ca"
    path: "fixie-ai/covost2"
    name: "en_ca"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "Catalan"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-es_en"
    path: "fixie-ai/covost2"
    name: "es_en"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-ru_en"
    path: "fixie-ai/covost2"
    name: "ru_en"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-zh_en"
    path: "fixie-ai/covost2"
    name: "zh-CN_en"
    splits:
      - "test"
    user_template: "Please translate the text to {{target}}. Your response should only include the {{target}} translation, without any additional words:\n\n<|audio|>"
    user_template_args:
      target: "English"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    num_samples: 15531
    eval_config:
      metric: "bleu"